default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 1234
  host: <%= ENV.fetch("DB_HOST") { "127.0.0.1" } %>

development:
  <<: *default
  database: e_commerce_api3_development

test:
  <<: *default
  database: e_commerce_api3_test

production:
  primary: &primary_production
    <<: *default
    database: e_commerce_api3_production
    username: e_commerce_api3
    password: <%= ENV["E_COMMERCE_API3_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: e_commerce_api3_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: e_commerce_api3_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: e_commerce_api3_production_cable
    migrations_paths: db/cable_migrate
